name: Android CI

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create Release?'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          mkdir -p "${RUNNER_TEMP}"
          echo -n "${ENCODED_KEYSTORE}" | base64 --decode > "${RUNNER_TEMP}/panda.jks"

      - name: Create keystore.properties
        run: |
          echo "STORE_FILE=${RUNNER_TEMP}/panda.jks" > keystore.properties
          echo "STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
          echo "API_KEY=${{ secrets.API_KEY }}" >> keystore.properties

      - name: Build APKs
        run: ./gradlew assembleRelease

      - name: Upload APKs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: echoir-apks
          path: app/build/outputs/apk/release/*.apk
          retention-days: 7

      - name: Create Release
        if: ${{ inputs.release }}
        env:
          GH_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          VERSION=$(grep -A5 'defaultConfig {' app/build.gradle.kts | grep 'versionName' | awk -F '"' '{print $2}')
          gh release create "v${VERSION}" \
            --title "Echoir v${VERSION}" \
            --notes "Release v${VERSION}" \
            app/build/outputs/apk/release/*.apk
